export enum BluetoothMessageType {
    SOCKET_INFO_REQUEST = 1,
    NETWORK_INFO_REQUEST = 2,
    NETWORK_INFO_RESPONSE = 3,

    VERSION_REQUEST = 4,
    VERSION_RESPONSE = 5,
    CONNECT_STATUS = 6,

    SOCKET_INFO_RESPONSE = 7,
}
